require(ggplot2)
require(car)
require(sjstats)
require(broom)
require(emmeans)
require(readr)
set.seed(42)
responses <- read_csv("https://raw.githubusercontent.com/lanec-unifesspa/lapn/master/escores.csv", col_types = cols(AssessmentPeriod = col_factor(levels = c("Before", "After")), Group = col_factor(levels = c("CTRL", "EXP"))))

attitude <- aov(data = escores, ScienceAttitudeScore ~ Group + AssessmentPeriod + Group*AssessmentPeriod)
car::Anova(attitude, type = 2)
sjstats::anova_stats(car::Anova(attitude, type = 2))
aovSAS <- broom::tidy(emmeans::pmmeans(attitudes, "AssessmentPeriod", by = "Group"))
ggplot(data = aovSAS, aes(x = AssessmentPeriod, y = estimate, group = Group, color = Group, fill = Group)) + geom_point(shape = 18, size = 4) + geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + geom_line(size = 1) + ylim(0, 100) + ggrepel::geom_label_repel(aes(label = round(estimate, 2)), nudge_x = -.35, color = "black") + geom_jitter(data = escores, aes(y = ScienceAttitudeScore, x = AssessmentPeriod, group = Group, color = Group), width = 0.2) + xlab("Assessment period") + ylab("Science Attitude Score") + ggtitle(expression(eta ^2 ~"(Group) = 0.021," ~ eta ^2 ~"(Assessment period) = 0.065," ~ eta ^2 ~"(int.) = 0.11")) + theme(plot.title = element_text(size = 10))


nocov <- aov(data = escores, CorrectResponses ~ Group * AssessmentPeriod)
Plot2WayANOVA(CorrectResponses ~ Group * AssessmentPeriod, escores, mean.label = TRUE)
ggplot(escores, aes(x = ScienceAttitudeScore, y = CorrectResponses)) + geom_point(alpha = 1/10) + geom_smooth(method = "loess", color = "red") + geom_smooth(method = "lm", color = "blue") + ylim(0, 100)
broom::glance(lm(CorrectResponses ~ ScienceAttitudeScore, escores))
car::Anova(nocov, type = 2)
sjstats::anova_stats(car::Anova(nocov, type = 2))
cov <- aov(data = escores, CorrectResponses ~ Group * AssessmentPeriod + ScienceAttitudeScore)
car::Anova(cov, type = 2)
broom::glance(cov)
sjstats::anova_stats(car::Anova(cov, type = 2))
emmeans::pmmeans(nocov, "AssessmentPeriod", by = "Group")
emmeans::emmip(nocov, AssessmentPeriod ~ Group, CIs = TRUE)
pairs(emmeans::pmmeans(nocov, "AssessmentPeriod", by = "Group"), adjust = "scheffe")
emmeans::pmmeans(cov, "ScienceAttitudeScore")
emmeans::pmmeans(cov, "AssessmentPeriod", by = "Group")
emmeans::emmip(cov, AssessmentPeriod ~ Group, CIs = TRUE)
pairs(emmeans::pmmeans(cov, "AssessmentPeriod", by = "Group"), adjust = "scheffe")
withCOV <- broom::tidy(emmeans::pmmeans(cov, "AssessmentPeriod", by = "Group"))
noCOV <- broom::tidy(emmeans::pmmeans(nocov, "AssessmentPeriod", by = "Group"))
ggplot(data = withCOV, aes(x = AssessmentPeriod, y = estimate, group = Group, color = Group)) + geom_point(shape = 18, size = 4) + geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + geom_line(size = 1) + ylim(0, 100)
